#!/bin/bash

STOCK_PATH="/Flash Tool/rom"


echo -e "\e[32m=========================
     FLASH TOOL
=========================\e[0m"

PS3='ESCOLHA UMA OPÇÃO DESSA LISTA: (1-12): '

options=("FLASHAR STOCK COMPLETA" "FLASHAR BL" "FLASHAR AP" "FLASHAR CP" "FLASHAR CSC" "FLASHAR UMS" "MOSTRAR VERSÃO" "SELECIONAR OPÇÃO NAND-ERASE" "SELECIONAR OPÇÃO PIT" "REINICIAR PARA O MODO NORMAL" "REINICIAR PARA O MODO DOWNLOAD" "SAIR")

select opt in "${options[@]}"
do
case $opt in
"FLASHAR STOCK COMPLETA") 
odin4 -a "${STOCK_PATH}/AP.tar"
    ;;
"FLASHAR BL")
    echo "Função FLASHAR BL ainda não implementada."
    ;;
"FLASHAR AP")
    echo "Função FLASHAR AP ainda não implementada."
    ;;
"FLASHAR CP")
    echo "Função FLASHAR CP ainda não implementada."
    ;;
"FLASHAR CSC")
    echo "Função FLASHAR CSC ainda não implementada."
    ;;
"FLASHAR UMS")
    echo "Função FLASHAR UMS ainda não implementada."
    ;;
"MOSTRAR VERSÃO")
    odin4 -v
    ;;
"SELECIONAR OPÇÃO NAND-ERASE")
    echo "Função SELECIONAR OPÇÃO NAND-ERASE ainda não implementada."
    ;;
"SELECIONAR OPÇÃO PIT")
    echo "Função SELECIONAR OPÇÃO PIT ainda não implementada."
    ;;
"REINICIAR PARA O MODO NORMAL")
    echo "Função REINICIAR PARA O MODO NORMAL ainda não implementada."
    ;;
"REINICIAR PARA O MODO DOWNLOAD")
    echo "Função REINICIAR PARA O MODO DOWNLOAD ainda não implementada."
    ;;
"SAIR")
    break
    ;;
*)
    echo "Opção inválida."
    ;;
esac
done
