#!/bin/bash

PS3='ESCOLHA UMA OPÇÃO: (1-2): '

echo -e "\e[35mSETUP - FLASH TOOL\e[0m"
echo "DESEJA CONTINUAR COM A INSTALAÇÃO?"

echo ""

options=("CONTINUAR INSTALAÇÃO" "ABORTAR")

select opt in "${options[@]}"
do
case $opt in
"CONTINUAR INSTALAÇÃO")
echo "INSTALANDO ODIN4 NO PATH DO SISTEMA..."
sleep 3
echo "INSTALANDO PLATFORM-TOOLS..."
sleep 3
sudo mv "/AresFlash-Tool/bin/odin4" /usr/bin/
sudo apt install adb fastboot
echo "TUDO PRONTO. VOCÊ JÁ PODE USAR A FERRAMENTA!"
;;
"ABORTAR")
echo "ABORTANDO SETUP..."
sleep 3
break
;;
esac
done
exit
